### ISSUE TITLE
Whether to consider supporting jupyter lab 3.5.3

### ISSUE THREAD

**Issue by zhoutianrui-tongji** [deshaw/jupyterlab-execute-time#106]
Dear developers,
   As you can see in the title, it is very important to me that I want to use your plugin in this version of jupyter lab. I dare not upgrade my jypyter lab, it will ruin my environment. Thank you! : )

**Comment by krassowski** [comment]
This extension does work with JupyterLab 3.5.3. I confirmed it by installing:

```
pip install jupyterlab==3.5.3 jupyterlab-execute-time
```

![image](https://github.com/deshaw/jupyterlab-execute-time/assets/5832902/693ba529-d927-4a40-b05d-5229548fdb8b)

Of note 3.5.3 is not supported by JupyterLab team. The latest supported JupyterLab release in 3.6.x branch is 3.6.6 release (and there is 4.0.x).

@zhoutianrui-tongji did you encounter any specific problem?

**Comment by zhoutianrui-tongji** [comment]
It really worked, I can't thank u more!  : ) 
Best wishes!
