### ISSUE TITLE
Feature Request: Show execution time on hover

### ISSUE THREAD

**Issue by ELind77** [deshaw/jupyterlab-execute-time#12]
Hi,

As a visually-compact alternative to showing timings underneath cells, would it be possible to render a tooltip of the timing information (possibly with some option to copy to clipboard) when hovering over a part of the cell (like the `In[\d]` `Out[\d]` bar on the left)?

-- Eric

**Comment by mlucool** [comment]
Thanks for the idea. I don't think there is an API to do that though. I'd be happy to review a PR if you find otherwise as another option for where this should display.

**Comment by ipcoder** [comment]
As may be a simpler alternative, to serve the compactness, may be to add a `minimal_time_show` parameter to show only in cells with execution time larger than that?

**Comment by ELind77** [comment]
@mlucool I'm not familiar with the APIs available. How much direct DOM interaction is available? 

@ipcoder a minimum time is an interesting alternative. Especially if you could pick the time per notebook. Since that distribution will change based on the project/data set.

**Comment by ipcoder** [comment]
I would set it to few hundreds ms. Most cells are well below that, so that solves the problem of real estate.

**Comment by mlucool** [comment]
Sorry for the delayed response.

> As may be a simpler alternative, to serve the compactness, may be to add a minimal_time_show parameter to show only in cells with execution time larger than that?

Minimum time would be easy to add to this codebase if it were global, but I'm not sure if there is any easy mechanism to set it per notebook. I would be happy to approve a PR that adds minimum time globally and depending on how you figure out per notebook, I don't have any high level objections.

> I'm not familiar with the APIs available. How much direct DOM interaction is available?
As for APIs, this extension has access to the `CodeCell`, so you'd have to look there to see if the required API is there. My guess is you can do something similar to what is already done to find/update the DOM (e.g. https://github.com/deshaw/jupyterlab-execute-time/blob/master/src/ExecuteTimeWidget.ts#L135) if the API is not there. You can also make an issue on JuptyerLab to expose the required API.

**Comment by mlucool** [comment]
@toonijn added display on hover in https://github.com/deshaw/jupyterlab-execute-time/pull/17. This will be released soon. Closing!

**Comment by mlucool** [comment]
Hi all. A minimum time (s) option has been added.
