### ISSUE TITLE
Use a theme CSS variable instead of a Material Design color for the highlight animation

### ISSUE THREAD

**Issue by joaopalmeiro** [deshaw/jupyterlab-execute-time#124]
Hi! 👋 

## Context

I am creating a JupyterLab theme and as `jupyterlab-execute-time` is one of the extensions used, I would like to be able to guarantee the customization of its styles completely using the CSS variables defined in JupyterLab themes.

## Problem

Currently, one of the colors used in the highlight animation is one of the Material Design colors and not one of the semantic colors defined in JupyterLab themes, for example: https://github.com/deshaw/jupyterlab-execute-time/blob/985728d1b9889f52a8c0f3a646739849c0f9bbac/style/base.css#L1-L9

## Possible solution

The Material Design color used, `--md-blue-100`, corresponds to `--jp-brand-color3` in the default JupyterLab themes:

- https://github.com/jupyterlab/jupyterlab/blob/v4.3.0a1/packages/theme-light-extension/style/variables.css#L222
- https://github.com/jupyterlab/jupyterlab/blob/v4.3.0a1/packages/theme-dark-extension/style/variables.css#L225
- https://github.com/jupyterlab/jupyterlab/blob/v4.3.0a1/packages/theme-dark-high-contrast-extension/style/variables.css#L225

So, a possible solution would be to change `var(--md-blue-100, #9fccff)` to `var(--jp-brand-color3, #bbdefb)`, using the [current Material Design color](https://github.com/jupyterlab/jupyterlab/blob/v4.3.0a1/packages/apputils/style/materialcolors.css#L82C18-L82C25) as a fallback.

Let me know your thoughts, please, and if I can open a PR. Thanks! 😄

**Comment by joaopalmeiro** [comment]
This seems like a perfect solution to me, @krassowski!

**Comment by krassowski** [comment]
Sounds good to me.

**Comment by joaopalmeiro** [comment]
@krassowski,cCan I go ahead and open a PR to propose this change, or should we wait for more feedback?
