### ISSUE TITLE
Execution duration doesn't show when using R kernel - only shows the datetime stamp

### ISSUE THREAD

**Issue by udaykapur** [deshaw/jupyterlab-execute-time#14]
**jupyterlab version:** 2.1.5
**IRkernel version:** 1.1.1
**Anaconda version:** Anaconda3-2020.07-Linux-x86_64
**R version:** R version 4.0.2 (2020-06-22) -- "Taking Off Again"
**Python version:** 3.8.3
**Node.js version:** 14.13.0
**Browser:** Firefox 81.0 (64-bit)

**OS info:** Ubuntu 20.04.1 LTS
![image](https://user-images.githubusercontent.com/15121710/94818783-d5b92c80-0441-11eb-9a14-7b2772b6787b.png)

**Output when using python3 kernel within jupyterlab**
![image](https://user-images.githubusercontent.com/15121710/94819550-bd95dd00-0442-11eb-9e2f-46d571cabdb1.png)

**Output when using R kernel within jupyterlab**
![image](https://user-images.githubusercontent.com/15121710/94820003-4d3b8b80-0443-11eb-9eae-048c228c3a04.png)

As can be seen from the above image, the extension only shows the datetime stamp when using R kernel but the execution duration is missing. Works fine for python kernel though. 

Please close this issue in case this is by design and the extension is not supposed to support R kernel at this stage (or for that matter any other kernel other than Python) - could not find anything on google hence opened the issue here.

Thanks

Edit: added text for clarity.

**Comment by mlucool** [comment]
Thanks for the detailed issue. While this has not been tested for R, there is nothing python specific about the design. Can you check if R is producing all the required metadata? In the screenshot below you can see what it looks like for python.

<img width="358" alt="Screen Shot 2020-10-03 at 8 51 48 AM" src="https://user-images.githubusercontent.com/1813603/94992148-f70b3d00-0555-11eb-9836-03672f16d200.png">

**Comment by udaykapur** [comment]
Thanks for looking into this - just checked and it appears some of the metadata is missing at my end. 

![image](https://user-images.githubusercontent.com/15121710/95029185-35d5fa00-06f2-11eb-926f-c9228dc3e387.png)

Maybe someone else can try and replicate on a system with different config to mine to validate this is the case for all R kernels regardless of the OS/R kernel version etc.

**Comment by octavd** [comment]
Hello @udaykapur , @mlucool ,

I've tested also this extension with R kernel and i am having the same issue *screenshot below*.

![image](https://user-images.githubusercontent.com/33294589/95371399-d559df00-08e2-11eb-9c79-ebb5c129416f.png)

I've tested this with IJulia kernel and having the same issue also.
Will test with more kernels.

**Comment by octavd** [comment]
Tested with PySpark / Spark / SparkR kernel and i confirm it works for all of them.

**Comment by mlucool** [comment]
This seems like the problem is the metadata the kernel outputs. @octavd @udaykapur can you please open an issue with the relevant kernels?

**Comment by udaykapur** [comment]
Just tried within a jupyter notebook instead of jupyter lab and the execution time shows up correctly using the same R kernel. Could this possibly be an issue with jupyter lab instead of the kernel?

![image](https://user-images.githubusercontent.com/15121710/95464788-1840b300-09c6-11eb-9f14-46bf744e5cf1.png)

**Comment by mlucool** [comment]
Notebook and lab use very different ways of getting the data. This plugin is a rewrite and uses the now standardized metadata from lab. If the data does not appear in the lab metadata, it will not render. This makes this likely a kernel issue.

**Comment by udaykapur** [comment]
Great, thanks for the clarification @mlucool. Will open an issue with the relevant kernel for this. 

@octavd - you might want to do the same with the IJulia kernel as well.

@mlucool - please feel free to close this issue, unless we want to wait for validation from some more users using different OS/kernel versions etc. while I get the IR kernel developers to look into this and see if they can help in the resolving the issue.

**Comment by octavd** [comment]
@udaykapur, issue was opened also for IJulia kernel. Hope this will be solved, i really like this jupyterlab extension.

**Comment by mlucool** [comment]
Thanks for logging those @udaykapur and @octavd. Seems like there is nothing to do here from the plugin POV. Please reopen if you need help.

**Comment by flying-sheep** [comment]
Hi! What do you mean with “standardized metadata from lab”? My Jupyter lab doesn’t add an `execution` dict to cell metadata.

**Comment by mlucool** [comment]
Hi @flying-sheep. You need to opt-in with [recordTiming](https://github.com/deshaw/jupyterlab-execute-time#jupyterlab-execute-time). The code for recoding this in lab can [be found here](https://github.com/jupyterlab/jupyterlab/blob/46908b566e84d2f025db509f0591b9d86522e796/packages/cells/src/widget.ts#L1056). Our code for determining start and end time can be [found here](https://github.com/deshaw/jupyterlab-execute-time/blob/master/src/ExecuteTimeWidget.ts#L141).

If you would like a to make PR that would support more kernels or protocol versions, we are happy to accept one!

**Comment by flying-sheep** [comment]
I’m not familiar with the code and have enough pet projects, but one would just have to figure out where in the lab code to insert a `const fallback = (new Date).toISOString()` to use when `!value`.

**Comment by mlucool** [comment]
@flying-sheep I tried that with [this patch](https://github.com/jupyterlab/jupyterlab/compare/master...mlucool:patch-3), but it seems the when I did a quick test, `shell.execute_reply` was never sent,

I see:
```
        "iopub.status.busy": "2020-10-19T16:48:25.616723Z",
        "iopub.execute_input": "2020-10-19T16:48:25.617425Z",
        "iopub.status.idle": "2020-10-19T16:48:25.630658Z"
```


Our time is calculated via `shell.execute_reply` - `iopub.execute_input` . It seems like I should use `iopub.status.idle` to determine the end for R. Is this correct?

**Comment by flying-sheep** [comment]
But it does send a `shell.execute_reply`!

When you set the env variable `JUPYTER_LOG_LEVEL=3` (in retrospect I should have called it `IR_LOG_LEVEL`), and execute a simple cell you see:

```
DEBUG: main loop: beginning
DEBUG: main loop: after poll. ZMQ code: 1; Errno: 11
DEBUG: main loop: shell
DEBUG: Sending msg iopub.status
DEBUG: Sending msg iopub.execute_input
DEBUG: Executing code: 1
DEBUG: Value output...
DEBUG: Sending display_data: List of 4
 $ text/html    : chr "1"
 $ text/markdown: chr "1"
 $ text/latex   : chr "1"
 $ text/plain   : chr "[1] 1"
DEBUG: Sending msg iopub.display_data
DEBUG: Code execution result: ok
DEBUG: Sending msg shell.execute_reply
DEBUG: Sending msg iopub.status
```

**Comment by mlucool** [comment]
Thanks for the tip @flying-sheep. I am fixing this in lab itself: https://github.com/jupyterlab/jupyterlab/pull/9206

**Comment by mlucool** [comment]
Thanks for confirming. Closing!
