### ISSUE TITLE
Adding a lot of noise when using jupytext

### ISSUE THREAD

**Issue by marcglobality** [deshaw/jupyterlab-execute-time#15]
I know maybe this should go to jupytext rather than here, but just asking if there's any way to avoid this to happen?

I'm getting stuff like

```
# %% execution={"iopub.status.busy": "2020-10-12T14:04:28.606426Z", "iopub.execute_input": "2020-10-12T14:04:28.606732Z", "iopub.status.idle": "2020-10-12T14:04:28.610404Z", "shell.execute_reply.started": "2020-10-12T14:04:28.606703Z", "shell.execute_reply": "2020-10-12T14:04:28.609343Z"}
import pandas

# %% execution={"iopub.status.busy": "2020-10-12T14:04:29.902223Z", "iopub.execute_input": "2020-10-12T14:04:29.902537Z", "iopub.status.idle": "2020-10-12T14:04:29.906057Z", "shell.execute_reply.started": "2020-10-12T14:04:29.902510Z", "shell.execute_reply": "2020-10-12T14:04:29.905227Z"}
print(pandas.__path__)
```

in the original py file, when running the notebook and sync with py file. I wonder if there's any way to keep the py free of this info (as that's the one I'm pushing to git)

**Comment by marcglobality** [comment]
I think I found the solution https://github.com/mwouts/jupytext/blob/master/docs/config.md#metadata-filtering so will close here and just leave it in jupytext. Sorry for the inconvenience

**Comment by mwouts** [comment]
Hi here, I think I've seen another extension that uses the cell metadata `ExecuteTime`. Would you be interesting in using the same metadata keys as that previous extension? If so, I can search among the previous issues of https://github.com/mwouts/jupytext/issues to find out which extension that was...

**Comment by mlucool** [comment]
Hi @mwouts. This plugin does not modify the notebook actually. It uses the already present metadata to render the output below a cell in a meaningful way. The metadata is added by jupyterlab itself and thus not plugin specific. You may be thinking of [this notebook](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/master/src/jupyter_contrib_nbextensions/nbextensions/execute_time) plugin which did store data in the ipynb. If you still think there is something we can do to make things more standard, we are open to it.

**Comment by mwouts** [comment]
Oh interesting! I see, `executetime` is the Jupyter
