### ISSUE TITLE
Execution Time is not shown

### ISSUE THREAD

**Issue by rschmidtner** [deshaw/jupyterlab-execute-time#19]
Hi Guys,

the extension is not working for me :(
I already tried to reinstall it, but it didn't help.

Jupyter lab version: 2.2.9
conda env of jupyter lab:
- ipykernel 5.3.4 
- python 3.9.1

Kernel of environment that is selected in jupyter lab notebook:
-  ipykernel 5.4.2 
- python 3.8.5

My Settings look like this:
![image](https://user-images.githubusercontent.com/67690427/102698535-549e5400-423e-11eb-866b-623a657518e7.png)

`jupyter labextension list` looks like this:
![image](https://user-images.githubusercontent.com/67690427/102698564-a646de80-423e-11eb-8da0-208d65f2338c.png)

The problem seems to be that my cells don't produce any metadata. If I run a cell with nothing inside but `print("Hello World")`I end up with his:
![image](https://user-images.githubusercontent.com/67690427/102699000-cf1ca300-4241-11eb-9daf-448f05f9a729.png)

Any suggestions what I could try?

**Comment by mlucool** [comment]
Hi,

Thanks for reporting this issue. The lack of metadata indicates this is a problem with lab, a dependency, or something about your setup and not this plugin. I'd suggest making an issue on https://github.com/jupyterlab/jupyterlab.

**Comment by rschmidtner** [comment]
Hi, thanks for the quick response!

I found out why the cells are not recording any time metadata. You can see in the screenshot above that I enabled time recording under 

> Settings-> Advanced Settings Editor-> Execute Time. 

However (like you correctly tell us to do in the docs) you need to enable cell timing in the notebook via 

> Settings-> Advanced Settings Editor-> **Notebook**. 

I'd rewrite the install section in the README like this to prevent others from making the same stupid mistake (I tried to make a PR for this, but I did not have the rights to push my branch to this repo).
> ## Install
> 
> ```bash
> jupyter labextension install jupyterlab-execute-time
> ```
> Note: for this extension to show anything, you need to enable cell timing in the notebook via
> > Settings -> Advanced Settings Editor -> **Notebook**: `{"recordTiming": true}
>

**Comment by mlucool** [comment]
Tried to make it clearer
