### ISSUE TITLE
Compatibility with Jupyterlab 3.0.0

### ISSUE THREAD

**Issue by harper357** [deshaw/jupyterlab-execute-time#20]
It seems like Jupyterlab 3.0.0 broke compatibility for a lot of extensions. 

From the [changelog ](https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html): 

> For existing extensions, there is a new `python -m jupyterlab.upgrade_extension` script that can be used to upgrade extensions.

**Comment by Jacques2101** [comment]
it means that we need to run `python -m jupyterlab.upgrade_extension` to continue using execute-time extension ? 

How if it is not the case ? 

Thx.

**Comment by mlucool** [comment]
Thanks for reporting. As you noted, this extension is not ready for 3.0 yet. The upgrader did not work out of the box, so it may take a bit of time.

**Comment by harper357** [comment]
@Jacques2101 No, that command is for the dev team, not the end-user.

If you don't absolutely need to, I would wait for a week or two on upgrading to Jupyterlab 3.0 as an end-user.

**Comment by mlucool** [comment]
Opened https://github.com/deshaw/jupyterlab-execute-time/pull/21. Please try this branch out and let me know if you run into issues

**Comment by harper357** [comment]
So far, things seem to be working on the jlab3 branch

**Comment by mlucool** [comment]
This has been release. Please use:
```
pip uninstall jupyterlab_execute_time
```

**Comment by marcglobality** [comment]
Hi, thanks for this amazing extension

I don't see how to make this work with Jlab3. I see

 ```
[LabBuildApp] JupyterLab 3.0.9
[LabBuildApp] Building in /Users/marctorrellassocastro/miniconda3/share/jupyter/lab
[LabBuildApp] Building jupyterlab assets (production, minimized)
[LabBuildApp] WARNING | The extension "jupyterlab-jupytext" is outdated.

[LabBuildApp] WARNING | The extension "jupyterlab-execute-time" is outdated.
```
any ideas? thanks!

**Comment by marcglobality** [comment]
ok, so I did `pip install jupyterlab-execute-time`, refreshed, and it now works! Thanks!
