### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by moble** [deshaw/jupyterlab-execute-time#22]
@mlucool I've set up a conda-forge recipe for the newest version of this package [here](https://github.com/conda-forge/staged-recipes/pull/13742).  I have two questions about this (and can't seem to ping you from over there, so here we are).

1. I [added your name](https://github.com/conda-forge/staged-recipes/pull/13742/files#diff-cea9ef7774cbefe6012f1c65f3facd6ad22989577e2b57ac20179c4b8774f5c8R53) as a package maintainer.  Please let me know if that's okay, and if there's anyone else who should go on there.  (Also, since this is your package, I really won't be offended if you want my name taken off that list for some reason.)

2. Conda-forge requires *some* tests.  I don't know how this works for things like jupyterlab, so I just copied the tests from the jupyterlab recipe.  Please let me know if there's anything that should be removed or added.

**Comment by mlucool** [comment]
Hi @moble. Thanks for setting this up!

1. You can leave my name. As for yours, so-long as you continue to do the legwork here, I thinks that's fine as it only claims you are a maintainer for the recipe and not the repo.
2. I think you'll want something closer to what we have in build: https://github.com/deshaw/jupyterlab-execute-time/blob/master/.github/workflows/build.yml#L32. This ensures the extension is installed correctly.

**Comment by moble** [comment]
Great.  The builds have finished with that line in the tests, and I've marked the PR as ready for review, so one of the conda-forge admins will probably get around to it in the next ~day.

I don't know if you've maintained a conda-forge feedstock before, but it's pretty simple.  After the first round, there's just one more thing to do (which I can take care of), and then it will always update automatically whenever the PyPI package updates.  (You'll get notifications every time that happens.)  If the requirements for this package ever change, we might need to adjust `recipe/meta.yaml` slightly.  But otherwise, there's basically nothing to do.

Thanks for a really important extension!
