### ISSUE TITLE
Version for Jupyterlab 2.2

### ISSUE THREAD

**Issue by aerioeus** [deshaw/jupyterlab-execute-time#26]
Hi is there a version for Jupyterlab < 3.0 available?

merci

**Comment by mlucool** [comment]
Yes, 2.x is supported. See the older version of the README: https://github.com/deshaw/jupyterlab-execute-time/tree/81a3efa68c7ce9a8298a013ad7eea2982d08a4af#install

`jupyter labextension install jupyterlab-execute-time`
