### ISSUE TITLE
Cannot install on jupyterlab v.3.0.7

### ISSUE THREAD

**Issue by jrossmann** [deshaw/jupyterlab-execute-time#27]
When trying to install the extension on jupyterlab v.3.0.7 I get the following error:
An error occured.
ValueError: The extension "jupyterlab-execute-time" does not yet support the current version of JupyterLab.

Conflicting Dependencies:
JupyterLab                  Extension      Package
>=3.0.4 <3.1.0              >=2.0.2 <3.0.0 @jupyterlab/application
>=3.0.4 <3.1.0              >=2.0.2 <3.0.0 @jupyterlab/notebook
>=3.0.2 <3.1.0              >=2.0.1 <3.0.0 @jupyterlab/settingregistry
See the log file for details:  /tmp/jupyterlab-debug-gwfadd40.log

[jupyterlab-debug-gwfadd40.log](https://github.com/deshaw/jupyterlab-execute-time/files/5994824/jupyterlab-debug-gwfadd40.log)

**Comment by mlucool** [comment]
Try again with 2.0.2. This should be fixed

**Comment by ilijaplusx** [comment]
Although I was able to install the extension, it doesn't seem to work. When I run a cell, no execution time is showing. In the settings it is stated that the extension is enabled.

Tried with JupyterLab 3.0.7 and 3.0.6. I've also tried other extensions, just to check if it's not a global extensions problem, but Kite eg seems to work well.

Here's the output of `jupyter labextension list`:
```
JupyterLab v3.0.6
/home/ubuntu/venvs/jupyter-test/share/jupyter/labextensions
        jupyterlab-execute-time v2.0.2 enabled OK (python, jupyterlab_execute_time)
        @kiteco/jupyterlab-kite v2.0.2 enabled OK (python, jupyterlab_kite)

/usr/local/share/jupyter/labextensions
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled OK (python, jupyterlab_widgets)
```

**Comment by mlucool** [comment]
Hi @ilijaplusx, did you follow the instructions in the README? https://github.com/deshaw/jupyterlab-execute-time#jupyterlab-execute-time

If you think timing data should be turned on by default, please chime in on https://github.com/jupyterlab/jupyterlab/issues/9510

**Comment by jrossmann** [comment]
Hi, works now fine for me. Thanks

**Comment by ilijaplusx** [comment]
Ahh, rookie mistake of mine! Sorry @mlucool for bothering you! Everything works nicely.
