### ISSUE TITLE
Execute time not showing in notebook with time stamps in the metadata

### ISSUE THREAD

**Issue by zyrxvo** [deshaw/jupyterlab-execute-time#32]
Hello,

I'm having issues getting this extension to work. I've tried my best to follow the instructions in the README using `pip install jupyterlab_execute_time` and making sure that I to enable cell timing in the notebook via Settings->Advanced Settings Editor->Notebook: `{"recordTiming": true}`.

The software versions that I'm using are

>`$ jupyter --version`
jupyter core     : 4.7.1
jupyter-notebook : 6.3.0
qtconsole        : 5.0.3
ipython          : 7.22.0
ipykernel        : 5.5.3
jupyter client   : 6.1.12
jupyter lab      : 3.0.14
nbconvert        : 6.0.7
ipywidgets       : 7.6.3
nbformat         : 5.1.3
traitlets        : 5.0.5

>jupyterlab-execute-time  : 2.0.2

I don't know if this is an issue with the M1 Apple Silicon. I'm running macOS 11.3 and I installed `Python 3.9.4` with `brew`.

The metadata is being recorded correctly, because the time stamps and wall times show up correctly when I open the notebook on a different machine that also uses `juypterlab-execute-time`. So it is not like [this issue](https://github.com/deshaw/jupyterlab-execute-time/issues/19). It's a new installation of `JupyterLab v3.0.14`, so I don't think I have any holdover issues like [this one](https://github.com/deshaw/jupyterlab-execute-time/issues/25). I tried running `jupyter labextension enable jupyterlab-execute-time`, but nothing changed, and when I list the extensions I'm using it doesn't return anything.
>`$ jupyter labextension list`
JupyterLab v3.0.14

I know there are a lot of issues and stackoverflow questions that have been opened involving the time not showing. This is the only extension that I use and I really appreciate the work that's been put into it. I'd be grateful for any help or insight. Let me know what kind of details you may need.

Thank you

**Comment by mlucool** [comment]
The help narrow this type of issue down, I added a console message to show the plugin was activated as part of https://github.com/deshaw/jupyterlab-execute-time/pull/33,. Can you install this plugin from git, then see if you see the following in the console of the browser?
>JupyterLab extension jupyterlab-execute-time is activated!

**Comment by zyrxvo** [comment]
Thank you for the help, it is not working yet.

I did the following things: 
>`pip uninstall jupyterlab-execute-time`
`git clone https://github.com/deshaw/jupyterlab-execute-time.git`
`cd jupyterlab-execute-time`
`git rev-parse HEAD`
`cedbe9eea466a1965d3b298f00c40f20f9bdcefe`
`pip install -e .`
`cd ..`
`jupyter lab build`
`jupyter lab`

I relaunched JupyterLab with the browser console opened and found (in Safari)
>[Debug] Starting application in workspace: "default" (jlab_core.26a554263e541eb0c66a.js, line 2)
[Debug] Starting WebSocket: ws://localhost:8888/api/kernels/f94263cd-e249-4f60-a718-c4ad25d51233 (jlab_core.26a554263e541eb0c66a.js, line 2)
[Debug] Starting WebSocket: ws://localhost:8888/api/kernels/f94263cd-e249-4f60-a718-c4ad25d51233 (jlab_core.26a554263e541eb0c66a.js, line 2)
[Debug] Starting WebSocket: ws://localhost:8888/api/kernels/f94263cd-e249-4f60-a718-c4ad25d51233 (jlab_core.26a554263e541eb0c66a.js, line 2)

and in Chrome
>Starting application in workspace: "default"
36[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
jlab_core.26a554263e541eb0c66a.js?v=26a554263e541eb0c66a:2 [Violation] 'requestAnimationFrame' handler took 74ms
default.js:65 Starting WebSocket: ws://localhost:8888/api/kernels/f74854fd-7984-4d50-bfe8-70b8aa0c498f
default.js:65 Starting WebSocket: ws://localhost:8888/api/kernels/f74854fd-7984-4d50-bfe8-70b8aa0c498f
default.js:65 Starting WebSocket: ws://localhost:8888/api/kernels/f74854fd-7984-4d50-bfe8-70b8aa0c498f

Let me know if this is the information that you were looking for and if these are the steps that you intended me to do.
In case it's helpful, the notebook cell metadata looks like this:
>{
    "execution": {
        "iopub.execute_input": "2021-04-30T19:55:13.039684Z",
        "iopub.status.busy": "2021-04-30T19:55:13.039325Z",
        "iopub.status.idle": "2021-04-30T19:55:13.107871Z",
        "shell.execute_reply": "2021-04-30T19:55:13.107478Z",
        "shell.execute_reply.started": "2021-04-30T19:55:13.039596Z"
    },
    "tags": []
}

**Comment by mlucool** [comment]
If `JupyterLab extension jupyterlab-execute-time is activated!` is not installed correctly.

Look like above doesn't have `jupyter labextension develop . --overwrite` nor `jlpm`. See [here](https://github.com/deshaw/jupyterlab-execute-time#contributing). You can try this instead to install from git via
```
pip install git+https://github.com/deshaw/jupyterlab-execute-time.git
```

**Comment by mlucool** [comment]
Glad it works. Closing.
