### ISSUE TITLE
Not compatible with JupyterLab 3.0.15

### ISSUE THREAD

**Issue by bobcolner** [deshaw/jupyterlab-execute-time#36]

**Comment by mlucool** [comment]
There is an issue with the build system right now. You can also try a dev build: https://github.com/deshaw/jupyterlab-execute-time#development-install

https://github.com/deshaw/jupyterlab-execute-time/pull/37 is an attempt to fix it, but something is still not working.

**Comment by mlucool** [comment]
Can you try `2.0.3` with lab@`3.0.16`? While mybinder does not seem to work yet, that combo did work for me.

**Comment by filipeaguiarrod** [comment]
Even in 3.0.14 looks that it's not working =(

**Comment by mlucool** [comment]
As a workaround, you can build from dev. See https://github.com/deshaw/jupyterlab-execute-time#contributing (this seems to be the same as https://github.com/deshaw/jupyterlab-execute-time/issues/32)

**Comment by bobcolner** [comment]
It works for me in lab Version 2.3.1

**Comment by mlucool** [comment]
This should work with the new release. Be sure for 3.x you are installing from python and not npm (e.g. `pip install jupyterlab_execute_time`).

Closing, but feel free to reopen if you still have an issue!
