### ISSUE TITLE
Display execution times when converting to html

### ISSUE THREAD

**Issue by marcglobality** [deshaw/jupyterlab-execute-time#43]
Hi, I really like this extension, but I cannot see the times when converting to html. Is there any way to get it? We use html's extensively to share notebook reports, and it's a shame losing this piece of info. 

I'm sure this is not just this extension but something bigger that I'm missing out

**Comment by mlucool** [comment]
Thanks for logging this. I'm not sure how we'd do that given the implementation. CC @goanpeca in case you have any ideas.

**Comment by goanpeca** [comment]
Inquiring about this!

**Comment by marcglobality** [comment]
I wonder... would it be possible to use nbconvert to turn into html and then parse the ipynb and add the info after each cell?

**Comment by goanpeca** [comment]
>the HTML export is done through nbconvert. So the information needs to be in the notebook file. And you probably need to add some processor to convert it to some meaningful html or else.

**Comment by marcglobality** [comment]
I did some exploration on this and it seems like your extension is doing the things on real time, but not storing the result on the notebook. There is this javascript piece  https://github.com/deshaw/jupyterlab-execute-time/blob/master/src/ExecuteTimeWidget.ts#L184

creating the text and calculating the time spent to run the cell, but in the notebook I just see
```
{
   "cell_type": "code",
   "execution_count": 2,
   "id": "checked-newspaper",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2021-06-17T10:43:31.023572Z",
     "iopub.status.busy": "2021-06-17T10:43:31.023288Z",
     "iopub.status.idle": "2021-06-17T10:43:31.582566Z",
     "shell.execute_reply": "2021-06-17T10:43:31.581958Z",
     "shell.execute_reply.started": "2021-06-17T10:43:31.023546Z"
    },
    "tags": []
   },
```
there's nothing about "last executed ...."

I guess I should add some postprocessor to nbconvert based on that JS, but I'm not so experienced in frontend stuff to make this work

**Comment by goanpeca** [comment]
>I did some exploration on this and it seems like your extension is doing the things in memory, but not storing the result in the notebook

I think that is the crux of it, the information needs to be stored so nbconvert can do something with it.

**Comment by marcglobality** [comment]
> > I did some exploration on this and it seems like your extension is doing the things in memory, but not storing the result in the notebook
> 
> I think that is the crux of it, the information needs to be stored so nbconvert can do something with it.

@goanpeca coming back to this after some time, as I still have the problem :D 

Do you have an idea how we could solve this?

**Comment by marctorsoc** [comment]
Hey @goanpeca, finally came back to this (this is my personal account). Now I have the metadata persisting in the cell's metadata thanks to this preprocessor:

```
from nbconvert.preprocessors import *
from datetime import datetime
from string import Template


class ExecutionTimePreprocessor(Preprocessor):
    """Adds message "Last executed" to the field execution_time of cell's metadata"""

    DATE_TEMPLATE = "%Y-%m-%dT%H:%M:%S.%fZ"

    def preprocess_cell(self, cell, resources, index):

        if "execution" in cell.metadata:
            start_str = cell.metadata.execution["iopub.execute_input"]
            end_str = cell.metadata.execution["shell.execute_reply"]

            start = datetime.strptime(start_str, self.DATE_TEMPLATE)
            end = datetime.strptime(end_str, self.DATE_TEMPLATE)

            template = Template(
                f"Last executed at {end.replace(microsecond=0)} in $time"
            )

            delta = end - start

            seconds = delta.seconds
            if seconds:
                milis = round(delta.microseconds / 1000)
                result = template.substitute(time=f"{seconds}.{milis}s")
            elif delta.microseconds > 1000:
                milis = round(delta.microseconds / 1000)
                result = template.substitute(time=f"{milis}ms")
            else:
                result = template.substitute(time=f"{delta.microseconds}us")

            cell.metadata.execution["execution_time"] = result

        return cell, resources
```

Not sure how to proceed from here. How do I write to the little status bar after the cell? Is that a widget? cc @mlucool

**Comment by mlucool** [comment]
If you are already writing cell processors, maybe you can  use a [display.HTML](https://stackoverflow.com/questions/25698448/how-to-embed-html-into-ipython-output) to add this as the first of the cell outputs? On the page, we are using some not so pretty-APIs to attach it to the input area.

**Comment by marctorsoc** [comment]
Thanks, I think I found a better way. I create a new template and add some jinja code after this line https://github.com/jupyter/nbconvert/blob/main/share/templates/lab/base.html.j2#L30 to surface the string I created with the preprocessor. I already got something ugly working

![image](https://user-images.githubusercontent.com/22045779/171296712-cf993d56-f2a1-4966-832c-818253660e99.png)

Now it's just a matter of styling

**Comment by marctorsoc** [comment]
this is now solved for me. Feel free to close the issue. And thanks for your help :)
