### ISSUE TITLE
Support for Jupyter Lab 3.1.x

### ISSUE THREAD

**Issue by bschulth** [deshaw/jupyterlab-execute-time#50]
Would be great to add support for Jupyter Lab 3.1.x ?

https://github.com/deshaw/jupyterlab-execute-time/blob/master/package.json#L59-L64

https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html#v3-1 

Thanks!

**Comment by mlucool** [comment]
This should work if you install it with the new directions: https://github.com/deshaw/jupyterlab-execute-time#install

**Comment by ZeyuSun** [comment]
The new direction says `pip install jupyterlab_execute_time` but I don't think it is working on my environment:
```plain
jupyterlab                    3.1.9
jupyterlab-execute-time       2.0.2
```

**Comment by mlucool** [comment]
Did you enable `recordTiming`?

**Comment by ZeyuSun** [comment]
Yes, I did. It's something else that is going wrong in my environment. I created a new one and it worked.

**Comment by Tabixe** [comment]
I was having this issue when trying to install the extension directly on the JupyterLab interface but the conda command worked smoothly. Thanks for this great tool!

**Comment by bschulth** [comment]
@mlucool, I can confirm this works if you install via pip:
```sh
# Works
/usr/bin/pip install jupyterlab-execute-time
jupyter lab build --log-level=DEBUG
jupyter labextension list
```

It fails when you try to install via `jupyter labextension`
```sh
# Fails
jupyter labextension install --no-build jupyterlab-execute-time
jupyter lab build --log-level=DEBUG
jupyter labextension list
```
And yes, @mlucool, I was already aware of the setting requirement:
 - `Settings- > Advanced Settings Editor -> Notebook: {"recordTiming": true}`

### Close the issue?
- I am happy to mark this issue closed, given that it works via pip install.

**Comment by sg-s** [comment]
@bschulth thanks, this works for me.

however, when i did this, something else broke, and i had to fix that using [this](https://github.com/jupyterlab/jupyterlab/issues/10228)
