### ISSUE TITLE
Can't install extension on jupyterlab 3.2.2

### ISSUE THREAD

**Issue by queirozfcom** [deshaw/jupyterlab-execute-time#57]
Any ideas? I tried looking at the dependencies  in `package.json` but the versions were up to date.

In `pyproject.toml` there's **this** `"jupyterlab~=3.0"` but the error message shouldn't be mentioning 2.x in any case

![image](https://user-images.githubusercontent.com/1554354/140830722-375e9e5d-3434-4431-96bb-0345dfb84919.png)

**Comment by mlucool** [comment]
lab@3 installs via pip now: https://github.com/deshaw/jupyterlab-execute-time#install

**Comment by queirozfcom** [comment]
Got it. thanks!
