### ISSUE TITLE
By clicking Ctrl+Z the execute time record(s) may fallback on Windows 10

### ISSUE THREAD

**Issue by DatumWorld** [deshaw/jupyterlab-execute-time#58]
Env:  Just a fresh install of  jupyterlab=3.2.4 and python=3.8.12  with conda, on windows 10 

Detail: Just some code as  the following picture,
![image](https://user-images.githubusercontent.com/24842100/145132179-336ef35d-58bf-4403-8f49-5d95f7334900.png)
 ![image](https://user-images.githubusercontent.com/24842100/145133609-c6331ee1-0b9d-4e10-8e45-1319c4124fd2.png)
1  run the code in the second cell for several times, the execute time record  will change.
  2  then by clicking Ctrl+Z on windows 10, the execute time record will go backward to last record(s) , not only the code, as it showed in the second picture.

Expect:
by clicking Ctrl+Z,  only the code will go backward to its last result(s), the execute time record keeps as it is now. Just as it behaves in Jupyterlab 2.2.9 .

Note: 
I have not tested it on Linux ,and if the execute time record will go forward by clicking short keys.

**Comment by mlucool** [comment]
This sounds like a bug related to https://github.com/jupyterlab/jupyterlab/issues/10791. Can you raise the issue there?

**Comment by DatumWorld** [comment]
> This sounds like a bug related to [jupyterlab/jupyterlab#10791](https://github.com/jupyterlab/jupyterlab/issues/10791). Can you raise the issue there?

Thanks for your help ! With the way mentioned there, the notebook works fine now.
