### ISSUE TITLE
Version installation Error

### ISSUE THREAD

**Issue by Novgorodcev** [deshaw/jupyterlab-execute-time#59]
I am running  jupyterlab version 3.0.14 and I am receiving the following error during installation:

Extension Installation Error
An error occurred installing <code>jupyterlab-execute-time</code>.

Error message:

The extension "jupyterlab-execute-time" does not yet support the current version of JupyterLab.

Conflicting Dependencies:
JupyterLab                  Extension      Package
>=3.0.9 <3.1.0              >=2.0.2 <3.0.0 @jupyterlab/application
>=3.0.9 <3.1.0              >=2.0.2 <3.0.0 @jupyterlab/notebook
>=3.0.5 <3.1.0              >=2.0.1 <3.0.0 @jupyterlab/settingregistry

**Comment by mlucool** [comment]
Please see new install directions (use pip): https://github.com/deshaw/jupyterlab-execute-time#install
