### ISSUE TITLE
Notebooks executed in Lab then papermill (nbclient) display incorrect durations

### ISSUE THREAD

**Issue by kevin-bates** [deshaw/jupyterlab-execute-time#60]
While investigating https://github.com/elyra-ai/elyra/issues/2387 I've found that notebooks executed via papermill (which derives from nbclient) doesn't record `shell.execute_reply.started` in the cell's execution metadata.  I'm assuming this is because `shell.execute_reply.started` is not in the [notebook format spec](https://nbformat.readthedocs.io/en/latest/format_description.html#cell-metadata).  This results in incorrect duration results since `shell.execute_reply.started` _does exist_ albeit relative to the last time the notebook was executed via Lab.

Since an `execute_input` response is essentially when the cell's execution is started ([using ipykernel as an example](https://github.com/ipython/ipykernel/blob/0ab288fe42f3155c7c7d9257c9be8cf093d175e0/ipykernel/kernelbase.py#L641-L650)), I'm hoping we could drop the use of `shell.execute_reply.started` and replace the cell's start calculation with the [fallback code already in place](https://github.com/deshaw/jupyterlab-execute-time/blob/2c3adf4be0eff039f4d5575cdd7253c8d1cdc616/src/ExecuteTimeWidget.ts#L188-L189).

Would that be a change the project would be willing to accept? 

Also, since `execute_input` may not be available (e.g., [if `silent` is enabled](https://github.com/ipython/ipykernel/blob/0ab288fe42f3155c7c7d9257c9be8cf093d175e0/ipykernel/kernelbase.py#L643-L645), again in ipykernel), should the `in` clause be discarded if the duration cannot be determined?

nbclient also uses local timestamps for each of the timing entries, but that's a different issue.

**Comment by kevin-bates** [comment]
Hi @mlucool,

> Based on above, it feels like something [nbclient] should clear all the execution metadata when rerunning a cell. This ensures that no old metadata is left around which may cause other bugs (e.g. at some point in time there is a new start with a previous end). If there is a valid reason that this is not possible, we'd be happy to accept a PR.

That's a fair point.  Do you know if Lab also clears the timing data?  

I only started here because the user experience could be fixed with the proposed change alone which, if Lab is updated to discontinue using `shell.execute_reply.started`, will be required anyway.

**Comment by mlucool** [comment]
It does when you clear the notebook via [clear execution](https://github.com/jupyterlab/jupyterlab/blob/086e088fdb3d56201915041aa4420b5312c8198c/packages/cells/src/model.ts#L753). It also does [when you execute a cell](https://github.com/jupyterlab/jupyterlab/blob/3ef0dfb655710bddf6d5700b3a116e8777bdd08d/packages/cells/src/widget.ts#L1096).

**Comment by mlucool** [comment]
Closing per  jupyter/nbclient#195
