### ISSUE TITLE
Show previous execution time

### ISSUE THREAD

**Issue by adrienpacifico** [deshaw/jupyterlab-execute-time#62]
Hi,
I would like to be able to have previous execution time to be displayed while a given cell is running. Let me know if you think it is possible to do that!

### Behavior

Currently, when a cell is executed:
1. The execution start time is displayed, till the execution is over.
2. Once terminated, both the time at which the cell execution terminated and how long it took is displayed.

What I would like to have:
1. If already executed, both the execution start time and the previous execution length are to be displayed.
2. Same as current behavior. 

### Reason for that

It often happens that for cells that take a long time to execute, I wonder how long it will take before it is over (e.g. 10 minutes or 2 hours). 
It would be nice to have that information for the previous cell execution to be displayed. You will not have that information if you run the cell before looking at the last execution time.

**Comment by mlucool** [comment]
This seems like a good idea as an opt-in feature. We'd be happy to accept a PR for it!

**Comment by stefansimik** [comment]
> Hi, I would like to be able to have previous execution time to be displayed while a give cell is running. Let me know if you think it is possible to do that!
> 
> ### Behavior
> Currently, when a cell is executed:
> 
> 1. The execution start time is displayed, till the execution is over.
> 2. Once terminated, both the time at which the cell execution terminated and how long it took is displayed.
> 
> What I would like to have:
> 
> 1. If already executed, both the execution start time and previous execution length to be displayed.
> 2. Same as current behaviour.
> 
> ### Reason for that
> It often happens that for cells that take a long time to execute, I wonder how long it will take before it is over (e.g. 10 minutes or 2 hours). It would be nice to have that information for the previous cell execution to be displayed. You will not have that information if you run the cell before looking at last execution time.

Exactly, the same feature I am missing every day, when working with long running cells.

Excellent practical idea 👍

**Comment by adrienpacifico** [comment]
@mlucool I do know javascript, but I can look at the code and try to hack it till it works. Would you be kind enough to list the different steps to implement that function?
Would someone be ready to help me?

I guess I should find where the message displaying the time of execution comes from, and try to include the previous execution time from "before the execution of the cell" info.

**Comment by raonyguimaraes** [comment]
I just came here cause I was looking for this feature. Would be really good to see this implemented. A dropdown list with the previously executed times for each cell. I would like to know the previous runtime of the current cell I'm executing cause they sometimes take up to 40min to run.
