### ISSUE TITLE
Extension Installation Error

### ISSUE THREAD

**Issue by ajmeese7** [deshaw/jupyterlab-execute-time#66]
The extension "jupyterlab-execute-time" does not yet support the current version of JupyterLab.

```
Conflicting Dependencies:
JupyterLab                  Extension      Package
>=3.4.3 <3.5.0              >=2.0.2 <3.0.0 @jupyterlab/application
>=3.4.3 <3.5.0              >=2.0.2 <3.0.0 @jupyterlab/notebook
>=3.4.3 <3.5.0              >=2.0.1 <3.0.0 @jupyterlab/settingregistry
```

If you could update this extension when you get the time I would really appreciate, I would love to use it on my system!

**Comment by mlucool** [comment]
Please see the install instructions which are up to date for 3.x: https://github.com/deshaw/jupyterlab-execute-time#install
