### ISSUE TITLE
[Feature Request] Implement real-time timer

### ISSUE THREAD

**Issue by maxima120** [deshaw/jupyterlab-execute-time#68]
Would be nice to have option to display actual running time of a cell execution. So it ticks say once per second, displaying how long the cell is running

I understand that I can "calculate" running time by looking at the current clock and the "Execution started at" value but it is not exactly convenient.

**Comment by stefansimik** [comment]
Exactly, what I was looking for too.

**Comment by mlucool** [comment]
We would be happy to accept a PR here with this being an opt-in feature.

**Comment by mlucool** [comment]
Fixed via #72 (see screencast).
