### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by zhenyuan992** [deshaw/jupyterlab-execute-time#75]
hello! this is an awesome extension and i would like to request/add a new feature:
![New Project](https://user-images.githubusercontent.com/12291964/198694468-f79594b3-15f6-43ad-a739-4870d111aec2.png)
basically, you get to see the previous execution details _along_ with the current one.

this is useful for me because i would like to see the previous execution time so that i know roughly when the new runs will end.

if this is a good idea, ill try to implement it and make a PR.
lmkwyt 😁

**Comment by mlucool** [comment]
3.1.0rc1 was recently release and includes this. I expect a final version to land in the next few weeks. See #72 for a screencast.

**Comment by zhenyuan992** [comment]
looks amazing! thanks for the time!
