### ISSUE TITLE
Jupyterlab api change in 4.0.0

### ISSUE THREAD

**Issue by schmidi314** [deshaw/jupyterlab-execute-time#82]
I just tried this plugin with the latest alpha of jupyterlab-4.0.0a35 and it won't work. I had a similar issue with my jupyterlab-scenes plugin. It was mainly the metadata api of the cell model like used here:

https://github.com/deshaw/jupyterlab-execute-time/blob/ce61432e91719a176a73a16d69859186114f5541/src/ExecuteTimeWidget.ts#L154

For me, the change looked typically like this:
![image](https://user-images.githubusercontent.com/74381262/223329245-6ace76f2-aac6-44c8-8030-b6aa7264a007.png)

Hope this helps...

**Comment by mlucool** [comment]
Thanks! We plan to upgrade in the near future. I would have thought it requires more to handle windowing (e.g. use tokens via https://github.com/jupyterlab/jupyterlab/pull/13639)

**Comment by mlucool** [comment]
Looks like you were mostly right :) https://github.com/deshaw/jupyterlab-execute-time/pull/83
