### ISSUE TITLE
Conda install error

### ISSUE THREAD

**Issue by moltra** [deshaw/jupyterlab-execute-time#86]
The package for jupyterlab_execute_time located at C:\Users\smsma\miniconda3\pkgs\jupyterlab_execute_time-2.3.1-pyhd8ed1ab_0
appears to be corrupted. The path 'site-packages/jupyterlab_execute_time/labextension/static/vendors-node_modules_css-loader_dist_runtime_api_js-node_modules_css-loader_dist_runtime_cs'
specified in the package manifest cannot be found.

CondaVerificationError: The package for jupyterlab_execute_time located at C:\Users\smsma\miniconda3\pkgs\jupyterlab_execute_time-2.3.1-pyhd8ed1ab_0
appears to be corrupted. The path 'share/jupyter/labextensions/jupyterlab-execute-time/static/vendors-node_modules_css-loader_dist_runtime_api_js-node_modules_css-loader_dist_runtime_c'
specified in the package manifest cannot be found.

`     active environment : autogpt_DA
    active env location : C:\Users\smsma\miniconda3\envs\autogpt_DA
            shell level : 2
       user config file : C:\Users\smsma\.condarc
 populated config files : C:\Users\smsma\.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.1=0
                          __win=0=0
       base environment : C:\Users\smsma\miniconda3  (writable)
      conda av data dir : C:\Users\smsma\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\smsma\miniconda3\pkgs
                          C:\Users\smsma\.conda\pkgs
                          C:\Users\smsma\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\smsma\miniconda3\envs
                          C:\Users\smsma\.conda\envs
                          C:\Users\smsma\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.3.1 requests/2.29.0 CPython/3.10.9 Windows/10 Windows/10.0.22000
          administrator : False
             netrc file : None
           offline mode : False`

**Comment by DS-Liu** [comment]
Installing using Conda falls, while using pip works

**Comment by mlucool** [comment]
Is this still an issue?
