### ISSUE TITLE
Execution TIme is not displayed

### ISSUE THREAD

**Issue by Wolfscowl** [deshaw/jupyterlab-execute-time#88]
I am completely new in python.
I have installed the extention via pip as well as conda. But the execution time is not displayed.

There is a tab "Execute Time" under Advance Settings and it is also activated, but I don't get any information about the execution time if i run a cell.

I am using juypterLab version 3.5.3.

I can't find the place where to enter {"recordTiming": true}.
For me it looks like this under setting:
![jupyterlab settings notebook](https://github.com/deshaw/jupyterlab-execute-time/assets/64498784/d0489437-940b-4e8d-a38b-971c29c657cd)
![jupyterlab settings notebook 02](https://github.com/deshaw/jupyterlab-execute-time/assets/64498784/4d5a60e5-3f8a-40cb-bfd9-ecc65a7824a9)

**Comment by mlucool** [comment]
Can you search for record?
![image](https://github.com/deshaw/jupyterlab-execute-time/assets/1813603/655cdf56-015b-4595-b773-1f6065f4d1e2)

**Comment by Wolfscowl** [comment]
Thanks for your reply.
here how it looks
![recordtime](https://github.com/deshaw/jupyterlab-execute-time/assets/64498784/afa4999d-77a3-43ba-8109-10d22327983e)

**Comment by yshung1971** [comment]
I got the same problem. My jupyter lab version is 3.6.4. I have installed this extension succesfully. And for my installation., the parameter recordTiming default is false. So I modified to true and saved the configuration as well. No matter I refreshed the jupyter lab in browser or restarted the jupyter lab, the cell executing time was still not showing below the cell.

**Comment by ianalis** [comment]
Same issue. Work around is to revert back to 3.6.3.

<img width="545" alt="image" src="https://github.com/deshaw/jupyterlab-execute-time/assets/5608227/463667ef-9cb5-4533-8755-a3eb55d6ab8a">

<img width="559" alt="image" src="https://github.com/deshaw/jupyterlab-execute-time/assets/5608227/9b58a83f-7fe3-49db-b313-4c65a0aef713">

**Comment by yshung1971** [comment]
Thanks ianalis, it works after downgraded jupyterlab_execute_time to version 2.3.1.

**Comment by lkytal** [comment]
Same here,  version 2.3.1 works while 3.0.0 not

**Comment by mlucool** [comment]
Per the changelogs, 3.0.0 only supports JupyterLab@4.x - https://github.com/deshaw/jupyterlab-execute-time/blob/master/CHANGELOG.md#300-2023-05-19

**Comment by gasdaf** [comment]
i revert back to v2.3.1, but it still can't display time in cell.

**Comment by gasdaf** [comment]
![2023-07-11 11_46_52-JupyterLab](https://github.com/deshaw/jupyterlab-execute-time/assets/42822254/d6c5fc3e-360d-4ab9-b489-6920e2bb15df)

**Comment by gasdaf** [comment]
> ![2023-07-11 11_46_52-JupyterLab](https://user-images.githubusercontent.com/42822254/252545428-d6c5fc3e-360d-4ab9-b489-6920e2bb15df.png)

i already setting user preference {"recordTiming":true}, but it still can't display execute time in cell.  how can i solve this problem

**Comment by foobar41** [comment]
Same issue here, cannot display the cell execution time after setting the `recordTiming` field to `true`.
Using jupyterlab version 4.0.2 with mamba. How do I resolve this

**Comment by krassowski** [comment]
> i revert back to v2.3.1, but it still can't display time in cell.

@gasdaf you have a pretty outdated JupyterLab installation. Since other users report 2.3.1 works with Lab 3.x, maybe they are using a newer version of Lab 3.x, e.g. 3.6.x?

**Comment by krassowski** [comment]
Pinning version of JupyterLab in:

https://github.com/deshaw/jupyterlab-execute-time/blob/d9be07175d00a204452777cea6e45f4a41f41505/setup.py#L44

and yanking 3.0.0 from PyPI is the simplest solution.

Another approach would be to release a 3.0.1 as cross-compatible with both Lab 3.x and 4.0. This should be feasible but a bit more involved on the maintenance and testing end.

**Comment by Dzakpasu** [comment]
Mine also worked when I downgraded to 2.3.1
