### ISSUE TITLE
jupyterlab 3.6.5 unable install jupyterlab-execute-time

### ISSUE THREAD

**Issue by cxlGiraffe** [deshaw/jupyterlab-execute-time#90]
hi, when i prepared to install jupyterlab-execute-time, i got the problem.How can i fix it?
<img width="782" alt="image" src="https://github.com/deshaw/jupyterlab-execute-time/assets/49860843/f620c62f-8ac1-47ec-9f17-e6c849c27ba9">

it show that jupyterlab >=3.6.5 <3.7.0, my version is 3.6.5。

**Comment by OsicKwon** [comment]
Hi,
Maybe this greate extension is not working in v3.6.5. Only in v4.0.3, I can see the execution timestamp in each cells unfortunately.

**Comment by rpm5099** [comment]
Any chance of tweaking a version of this plugin to work with jlab >=3.7.0 <3.6.4?  Those are the versions lf jlab that MANY people are on right now and will continue to be for some time.

**Comment by mlucool** [comment]
Hi.

We plan to yank 3.0.0 for one that locks 3.0.1 to lab@4. This should let pip install the right thing. Sorry for the confusion!

**Comment by mlucool** [comment]
This was fixed with yanking 3.0.0 and releasing 3.0.1.

**Comment by rpm5099** [comment]
Thank you for being responsive on that, it is greatly appreciated
